### ISSUE TITLE
FileTooLargeException when user set ini setting to -1 value

### ISSUE THREAD

**Issue by Folcmon** [delight-im/PHP-FileUpload#1]
File uploader throw exception when user set limit resources to unlimited (-1).

example : 
```
if ($data['size'] > $this->maxIndividualSize) {
      : \tthrow new FileTooLargeException();
      : }
```
maybe something like that:
```
	public function withMaximumSizeInBytes($size) {
		$size = (int) $size;
		if ($size > $this->maxTotalSize &&($this->maxTotalSize != -1)) {
			throw new TotalSizeExceededError();
		}

		$this->maxIndividualSize = $size;

		return $this;
	}
```
?

**Comment by ocram** [comment]
Thanks a lot!

The handling of `memory_limit` has been fixed in https://github.com/delight-im/PHP-FileUpload/commit/c87735e61cafd5065892bd4a5c0a4369e1bd9847 and the handling of `post_max_size` has been fixed in https://github.com/delight-im/PHP-FileUpload/commit/d11fcb4c17d286534183417ab31dd3c376c681ee. Does that solve the issue for you?

Using Composer, you can update the library like this:

```
$ composer update delight-im/file-upload
```

From what I can see, it should be fine now. If not, please feel free to re-open.

By the way, please note that you still cannot pass `-1` to `withMaximumSizeInBytes`. For that use case, you can pass `\PHP_INT_MAX` instead.

**Comment by Folcmon** [comment]
Hello Marco!

Sorry for my late response but I have holiday and I was totally offline till now:). Thanks for update and quick fix this issue!! I also found one thing which can be potentially issue. I mean about case when we send file without extension after do after filename example : „”awesomeFileName” instead of awesomeFileName.jpeg maybe you should consider discovering file type by its mime and after that map mime type to proper extension? What do you think?

Best regards
Kamil

**Comment by ocram** [comment]
No problem!

Filenames without any extension and how we handle them might indeed become something that we should reconsider. For now, I haven't experienced any problems.

Please just open a new, separate issue if you encounter any problems with such filenames. Thanks!
