### ISSUE TITLE
I am getting error while setting max file size.

### ISSUE THREAD

**Issue by dpkrai96** [delight-im/PHP-FileUpload#2]
I am getting error while setting max file size at this line delight-im \ file-upload \ src \ AbstractUpload.php on-line 59

**Comment by dpkrai96** [comment]
When remove the file setting option it will successfully upload the file.

**Comment by ocram** [comment]
Thanks for pointing to the specific file and line number, which was helpful. Next time, if you could even quote the exception and stack trace, that would be even better.

It seems you tried to set the maximum file size for an individual upload via the `withMaximumSizeInBytes` method, but that value was too large. That’s because it was larger than `post_max_size`, `memory_limit` or `upload_max_filesize` from your `php.ini`. You can check these values using the `phpinfo` method.

The exception is thrown because the size that you specified would not have any effect. It would be useless because you have stricter limits in your PHP configuration already.

Does that help?
